# Generated by Django 3.2.5 on 2023-11-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20231130_0229'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('author', 'question'), name='unique_answer_user_question'),
        ),
    ]
